### ISSUE TITLE
Ubuntu 18.04 64bits compilation problem

### ISSUE THREAD

**Issue by aurimrv** [bright-tools/ccsm#115]
Please, does someone have a compiled version of CCSM for Ubuntu 18.04 64 bits? I am having a problem to compile it in my system.

**Comment by aurimrv** [comment]
I am getting the following error message during make:

$ /local/tools/ccsm/build$ make
...
[ 87%] Linking CXX executable ../../../../bin/ccsm
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: Na função "_start":
(.text+0x20): referência não definida para "main"
collect2: error: ld returned 1 exit status
tools/clang/tools/ccsm/CMakeFiles/ccsm.dir/build.make:98: recipe for target 'bin/ccsm' failed
make[2]: *** [bin/ccsm] Error 1
CMakeFiles/Makefile2:28315: recipe for target 'tools/clang/tools/ccsm/CMakeFiles/ccsm.dir/all' failed
make[1]: *** [tools/clang/tools/ccsm/CMakeFiles/ccsm.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
$ 

I am using GCC version 

$ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by bright-tools** [comment]
Sorry to hear that you're having problems.  Let me take a look & see if I can work out what the issue is.

**Comment by aurimrv** [comment]
Thank you very much. I appreciate a lot once the tool provides several metrics I am very interested in experimental purpose. All the best

**Comment by bright-tools** [comment]
Unfortunately I can't seem to quite reproduce what you're seeing.  However,
1. I've (added a script)[https://github.com/bright-tools/ccsm/blob/master/README.md#quick-start] to help build ccsm on Linux - all that should be needed is to clone the repo & run the script.
1. I've uploaded a (binary for Ubuntu 18.04 64-bit)[https://github.com/bright-tools/ccsm/releases/tag/v0.6], based on the latest code.
Please let me know how you get on.

**Comment by aurimrv** [comment]
Thank you very much. The binary is working fine. Cheers
