### ISSUE TITLE
Didn't find realpath / command not found: ccsm

### ISSUE THREAD

**Issue by hfabisiak** [bright-tools/ccsm#116]
Build has completed. Running new script, I get those results: 

Checking for cmake
Checking for svn
Checking for grep
Checking for realpath
Didn't find realpath

Terminal doesn't find ccsm command

**Comment by bright-tools** [comment]
The script uses the realpath command to work out an absolute path - looks like it's not installed on your system.  If you're running Debian or Ubuntu, `apt-get install realpath` should resolve that.
