### ISSUE TITLE
Passing parameters to clang

### ISSUE THREAD

**Issue by Gweld** [bright-tools/ccsm#118]
I want to use ccsm on code that uses header files, located in another directory, co clang does not see them, until I use clang -I /path/to/header/files/ is any option to ccsm pass this arg to clang ?

**Comment by bright-tools** [comment]
Hi @Gweld 

You can also pass parameters to clang by using `--` to separate the ccsm parameters (before) and clang parameters (after), e.g. :

```
ccsm.exe test.c  -- -I/the/path/to/my/headers
```

Hope that Helps.
