### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by nikolakolarovic** [bright-tools/ccsm#119]
LLVM has changed CMake syntax recently, and uses `add_clang_subdirectory` instead of `add_subdirectory`. However if I change it it still doesn't pick up ccms from tools/clang/tools/CMakeLists.txt.

**Comment by bright-tools** [comment]
Hi @nikolakolarovic 

I don't believe that `add_clang_subdirectory` will work for this case, unfortunately, as it requires that the directory being added is a child of the current directory (i.e. can't use it to add out-of-tree directories as is currently being done).  CCSM should still build using `add_subdirectory` (I've just done builds from clean on Windows & Ubuntu).  

Looking at the [README.md](README.md), though, I see that it wasn't correct.  It said:

> You will need to modify the path to point to wherever your clone of the CCSM project is, but note that the path in the first line should point to the 'src' sub-directory of the clone

but should have said:

> You will need to modify the path on the first line to point to wherever your clone of the CCSM project is (it should point to the parent of the 'src' directory)

Could this explain the problem which you were having?

**Comment by nikolakolarovic** [comment]
Thanks to your comment I have resolved my build issue. I just assumed that I should switch to `add_clang_subdirectory` without actually trying good old `add_subdirectory`.

After resolving the issue with MiniCSV (current version utilises `mini::csv::` namespace, not just `csv::`) compiling succeeds as part of Clang/LLVM.

Thanks for your help and for creating this great tool!
