### ISSUE TITLE
cannot build with errors

### ISSUE THREAD

**Issue by ajax4sec** [bright-tools/ccsm#121]
Hi, I tried to build the project ccsm with the instruction in Quick Start but failed. Could you help me? My system is Ubuntu 16.04, gcc version is 5.4.0 and clang version is 10.0.0. 
The errors are:
**error:** conflicting return type specified for ‘virtual clang::ASTFrontendAction* ASTFrontendActionFactory::create()’
   clang::ASTFrontendAction *create() override { 
**error:**   overriding ‘virtual std::unique_ptr<clang::FrontendAction> clang::tooling::FrontendActionFactory::create()’
   virtual std::unique_ptr<FrontendAction> create() = 0;

**error:** conflicting return type specified for ‘virtual clang::ASTFrontendAction* PPFrontendActionFactory::create()’
   clang::ASTFrontendAction *create() override { 
**error:**   overriding ‘virtual std::unique_ptr<clang::FrontendAction> clang::tooling::FrontendActionFactory::create()’
   virtual std::unique_ptr<FrontendAction> create() = 0;

**error:** cannot convert ‘MetricPPConsumer*’ to ‘clang::ASTFrontendAction*’ in return
    return new MetricPPConsumer( m_topUnit, m_options, m_srcMap, m_expanded );

**Comment by bright-tools** [comment]
Looks like the upstream clang API has changed.  I'll update ccsm shortly, thanks for letting me know.

**Comment by bright-tools** [comment]
@ajax4sec Should be fixed now - please re-open the issue if you have any problems.  Thanks!

**Comment by ajax4sec** [comment]
Thanks!
