### ISSUE TITLE
TRY hello_world error

### ISSUE THREAD

**Issue by ajax4sec** [bright-tools/ccsm#123]
Hi,
I have successfully compiled the project and run the example. However, there is an error of "fatal error: 'stddef.h' file not found" when I tried the "hello_world" in C language. I have seen the instruction for std libraries and found the options of "--exclude-std-headers". However it seems not working. Do you have any suggestions for that? Thanks!

**Comment by bright-tools** [comment]
You'll need to satisfy the include dependency in order for CCSM to be able to process the file.

The simplest way to do this is to clone https://github.com/bright-tools/c_headers which should provide a minimal, "clean" set of the standard C headers.  Then make sure that the `include` directory is included on the CCSM command line, e.g.

```
ccsm hello_world.c -- -I ../path/to/git/clone/location/include
```

Let me know if that helps or not.

**Comment by ajax4sec** [comment]
Thanks for the reply. I should set the linked parameter to the specific folder C90 or C99. My mistake and thanks again.
