### ISSUE TITLE
Excluding stdlib.h

### ISSUE THREAD

**Issue by pmbdk** [bright-tools/ccsm#124]
I am trying to analyze a larger project, starting with small parts of the code.

I am using v0.6 snapshot from https://github.com/bright-tools/ccsm/releases/tag/v0.6 (I know this is not the latest edition, but I just wanted to be up and running quickly to see what I could expect)

I am using --exclude-file=stdlib.h but still I get the following error:
C:\data\test_source.c:5:10: fatal error: 'stdlib.h' file not found

Is there a way to avoid this?

**Comment by bright-tools** [comment]
As CCSM's using a compiler front-end it needs the code under examination to be compilable, so it needs to be able to access all included files.  The `--exclude-file` option is used to exclude a file from the results analysis, but it's still needed.

In this case I'd suggest downloading the "vanilla" header files from https://github.com/bright-tools/c_headers/tree/master/include/c90 and using those as "place holders" to perform the analysis.  [This issue](https://github.com/bright-tools/ccsm/issues/123) has some further details which might be helpful.

Let me know if you're still having problems.

**Comment by bright-tools** [comment]
Closing this for now; please let me know if you're still having issues.
