### ISSUE TITLE
Path counting incorrect for conditional statements with return

### ISSUE THREAD

**Issue by mringwal** [bright-tools/ccsm#125]
If a conditional statement always exits the function, it should not be treated as a path multiplier.

Example:  PATH = 32 (2 ^ 5), but should be 6 (5+1) -- one of the 5 ifs is entered or none.

```
void fn_ifs_with_return(int i){
    if (i == 1){
        // i == 1
        return;
    }
    if (i == 2){
        // i == 2
        return;
    }
    if (i == 3){
        // i == 3
        return;
    }
    if (i == 4){
        // i == 4
        return;
    }
    if (i == 5){
        // i == 5
        return;
    }
}
```

I'm looking at MetricsMatcher.cpp, which already tracks if all subpaths have returns, but I haven't figured out, how to fix it yet. Will keep trying.

**Comment by bright-tools** [comment]
Thanks for spotting & reporting.  I'll take a look in the near future if you don't have any success.

**Comment by mringwal** [comment]
I'm still puzzled about how to do that properly. It looks easier to count paths on a control flow graph / acyclic graph than on the AST - but that's what we've got. 

I've looked around and didn't find much (asides from enterprise tools that I couldn't test). OClint ignores the returns as well as checkstyle (a java static analyzer).

An if statement with an return in one case should not be treated as x2 by a compound statement with multiple statement, but a first try to count it as x1 and additional sum up the returns didn't work either.

**Comment by mringwal** [comment]
Interesting paper by a company selling static analysis and metrics tools:
https://arxiv.org/pdf/1610.07914.pdf

Looks like you've correctly implemented NPath as described in the original 1988 paper, but that doesn't account for early returns.

**Comment by mringwal** [comment]
Fixed by merged pull request.
