### ISSUE TITLE
FUNC_NESTING with if-else-if cascade

### ISSUE THREAD

**Issue by mringwal** [bright-tools/ccsm#133]
It looks like CCSM treats if-else-if cascades (e.g. if switch cannot be used), as a all ifs nested into each other.

Example:

    void else_ifs(int i){
        if (i == 1){
        }
        else if (i == 2){
        }
        else if (i == 3){
        }
        else if (i == 4){
        }
        else if (i == 5){
        }
    }

I would expect to get a nesting level of 1, but CCSM returns 5 instead.

I guess it is counted like this:

    void else_ifs(int i){
        if (i == 1){
        }
        else {
            if (i == 2){
            }
            else {
                if (i == 3){
                }
                else {
                    if (i == 4){
                    }
                    else {
                        if (i == 5){
                        }
                    }
                }
            }
        }
    }

**Comment by bright-tools** [comment]
Thanks for the issue report.  You're right - the're currently no special handing for "else if"s.  #138 is in progress to address this.

**Comment by mringwal** [comment]
You're welcome. In our case, the if-else chain was comparing a variable to a list - and as the values had not been 'const enough', using a switch wasn't possible. We ended up, rewriting the code such that the value became #defines and were able to use a switch (so, the if-else-chain is gone).

You could add my trivial example to your tests - it's quite short.

**Comment by mringwal** [comment]
Thanks!
