### ISSUE TITLE
can not find MiniCSV.h

### ISSUE THREAD

**Issue by Chaoqun-Guo** [bright-tools/ccsm#142]
Sorry to disturb you, MiniCSV.h cannot be found during project compilation, how to solve it?

**Comment by bright-tools** [comment]
Hello!

`MiniCSV.h` is provided via a git sub-module.  Either you can clone the repo using the [--recursuve-submodules](https://github.com/bright-tools/ccsm/blob/master/docs/build_and_code.md#quick-start) option or you can run 
```
git submodule init
git submodule update
```
If you've already cloned.

That should pull in the MiniCSV sub-module.

**Comment by Chaoqun-Guo** [comment]
Thank you, the problem encountered has been resolved, I copied the minicsv.h from https://github.com/shaovoon/minicsv/archive/v1.7.11.tar.gz to the relevant folder, ccsm is a POWERFUL TOOL.
