### ISSUE TITLE
Path counting incorrect for break and continue in loops

### ISSUE THREAD

**Issue by mringwal** [bright-tools/ccsm#146]
If there's a condition in a loop that always leads to a break or a continue statement, I think it should not be treated as a multiplier for the path.

Example:
```
void fn_loop_break(int a){
	while (1){
		if (a == 0){
			break; // 1
		}
		if (a == 1){
			break; // 2
		}
		if (a == 2){
			break; // 3
		}
		break;	// 4
	}
        // 5 (not entering the while loop)
}
```

I would say that there are 4-5 possible paths to this, while ccsm reports 9.

Similarly, ccsm also reports a path count of 9 if we replace the break statments with continue.

```
void fn_loop_continue(int a){
	while (1){
		if (a == 0){
			continue; // 1
		}
		if (a == 1){
			continue; // 2
		}
		if (a == 2){
			continue; // 3
		}
		break;	// 4
	}
}
```

Finally, if we replace the breaks with a return statement, ccsm reports 5 which is as expected.

**Comment by bright-tools** [comment]
@mringwal thanks for the bug report. I agree that there seems to be an issue here. Will take a look soon.

**Comment by bright-tools** [comment]
Apologies for being so slow on this; I believe this issue should now be addressed.

**Comment by mringwal** [comment]
Thanks for taking a look and working on this. I'll try to compile it in the next days and confirm the fix

**Comment by mringwal** [comment]
Compiling CCSM / LLVM seems to got simpler, or at least not more complex. Just pulling and doing a new compile worked out of the box. I can confirm that the fix works for the test cases in tests/src/paths_mixed.c. Thanks!

**Comment by keestux** [comment]
This issue can be close, no? See my comment in [PR150](https://github.com/bright-tools/ccsm/pull/150)

**Comment by mringwal** [comment]
Sure! Thanks for tidying up.
