### ISSUE TITLE
Build error with llvm 3.7.0

### ISSUE THREAD

**Issue by keestux** [bright-tools/ccsm#63]
Hello,

Today I found this interesting tool and I tried to build it. The readme does no describe the build procedure, but I figured that I must build it by adding it to llvm/tools/clang/tool. With LLVM 3.7.0 the build error is
```
[ 85%] Building CXX object tools/clang/tools/ccsm/CMakeFiles/ccsm.dir/MetricMatcher.cpp.o
/src/llvm/llvm/tools/clang/tools/ccsm/MetricMatcher.cpp: In member function ‘void MetricVisitor::DeclCommon(const clang::DeclContext*, const clang::Decl*)’:
/src/llvm/llvm/tools/clang/tools/ccsm/MetricMatcher.cpp:476:36: error: no matching function for call to ‘MetricVisitor::HandleLoc(clang::SourceLocation)’
   HandleLoc( p_decl->getLocation() );
                                    ^
/src/llvm/llvm/tools/clang/tools/ccsm/MetricMatcher.cpp:476:36: note: candidate is:
In file included from /src/llvm/llvm/tools/clang/tools/ccsm/MetricMatcher.cpp:19:0:
/src/llvm/llvm/tools/clang/tools/ccsm/MetricMatcher.hpp:57:7: note: void MetricVisitor::HandleLoc(clang::SourceLocation&)
  void HandleLoc( clang::SourceLocation& p_loc );
       ^
/src/llvm/llvm/tools/clang/tools/ccsm/MetricMatcher.hpp:57:7: note:   no known conversion for argument 1 from ‘clang::SourceLocation’ to ‘clang::SourceLocation&’
```

**Comment by bright-tools** [comment]
Hi Kees,

Thanks for the feedback.  I got somewhat bogged down a while ago while working on #38 - it involved a fairly significant amount of change which also meant spending quite some time writing new test cases.  I've pulled the code from that branch back to the master, so you should be able to build against  LLVM 3.7 now.  Let me know if you have any problem.

Be aware, too, that this project is a work-in-progress - I'm currently trying to write test cases for all of the metrics, but it's something of a slow job!  If you've got any feedback, though, it'd be gratefully received.

**Comment by keestux** [comment]
OK Thanks.
That compilation problem is solved. There is one other thing I didn't mention. In MetricOptions.cpp I need an include of `<algorithm>`. Otherwise it fails to build with:
```
  /src/llvm/llvm/tools/clang/tools/ccsm/src/MetricOptions.cpp:67:6: error: ‘find’ is not a member of ‘std’
    ( std::find( ExcludeFunctions->begin(), ExcludeFunctions->end(), p_fn ) == ExcludeFunctions->end() ));
      ^
```

Oh, and BTW. I've build the whole LLVM tree from the GIT repos (mirrors of subversion) and included ccsm inthere. That works for me too.

**Comment by bright-tools** [comment]
Thanks for letting me know - hopefully fixed now.  Can I ask what toolchain you're using to build LLVM/ccsm?

**Comment by keestux** [comment]
This is GCC 4.8.4 on Ubuntu 14.0.x.

**Comment by keestux** [comment]
And a note about commit messages. The convention is described here: https://git-scm.com/book/ch5-2.html.
> As a general rule, your messages should start with a single line that’s no more than about 50 characters and that describes the changeset concisely, followed by a blank line, followed by a more detailed explanation.
Many GIT tools rely on that convention. Try, for example, `git log --oneline`, and see how certain lines are way too long.

**Comment by bright-tools** [comment]
Thanks - I'm still a newb when it comes to git, so the tip is appreciated.
