### ISSUE TITLE
HIS metric CALLS does not count unique function calls

### ISSUE THREAD

**Issue by keestux** [bright-tools/ccsm#75]
Hi,

In the readme there is a table with details about supported HIS metrics. It says:

| `CALLS`  | Implemented - `OP_FN_CALL_CNT` | Number of different functions called.  Note that functions called via function pointer are not counted |

Notice the part that says: _different function calls_
Currently this is not the case. It does not distinguish uniqueness.

**Comment by bright-tools** [comment]
Thanks - the documentation does indeed point to the wrong metric.  It should be OP_FN_CALL_UNIQUE_CNT, I believe.
