### ISSUE TITLE
CSV output is not correct

### ISSUE THREAD

**Issue by keestux** [bright-tools/ccsm#78]
Hi,

The generated CSV/TSV is not correct. In MetricDumper::dump there are two loops, one for the field names and one for the field values. Both loops must match for the generation of the separators.

Currently, the second loop that generates the values, only outputs separators for the fields that it outputs. And it only outputs a field value if it is relevant for the item.

You can already see the effect for item "Global". Here is an example
```
Name,Return points,Comment density,McCabe complexity,Modified McCabe...
Global,0.586,42,,10242,,
```

**Comment by bright-tools** [comment]
Believe this to be fixed now - please let me know if you still experience any problems.
