### ISSUE TITLE
MetricOptions::m_optionsOk not initialized properly

### ISSUE THREAD

**Issue by keestux** [bright-tools/ccsm#88]
In commit 7a58c2ba a new class member was added m_optionsOk. But is (implicitely?) initialized to false. And there is no code that makes it true. There is only code that sets it to false.

**Comment by bright-tools** [comment]
Thanks for spotting - 1/2 baked change on my side.  As it's not explicitly initialised, my understanding is that the C++ standard says the member won't be initialised with any particular value (as it's a primitive type).  Within VC builds it gets initialised to 0xCD (default memory value from heap), so it always initialises to `true`, but I fully expect different behaviour on other platforms/compilers.
